name       : haskell-typed-process
version    : 0.2.2.0
release    : 1
source     :
    - http://hackage.haskell.org/package/typed-process-0.2.2.0/typed-process-0.2.2.0.tar.gz : 42ed06889c15aa07577a0e8e3632659e343be95b77afa252b48b592ff7dbcf30
license    : MIT
component  : programming.haskell
summary    : Run external processes, with strong typing of streams
description: |
    Run external processes, with strong typing of streams
builddeps  :
    - haskell-async
    - haskell-cabal-install
    - haskell-stm
networking : yes
setup      : |
    sed -i "s|Custom|Simple|" typed-process.cabal
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
