name       : haskell-typed-process
version    : 0.2.6.0
release    : 2
source     :
    - https://hackage.haskell.org/package/typed-process-0.2.6.0/typed-process-0.2.6.0.tar.gz : 31a2a81f33463fedc33cc519ad5b9679787e648fe2ec7efcdebd7d54bdbbc2b1
license    : MIT
component  : programming.haskell
summary    : Run external processes, with strong typing of streams
description: |
    Run external processes, with strong typing of streams
builddeps  :
    - ghc-devel
    - haskell-async-devel
    - haskell-cabal-install
    - haskell-unliftio-core-devel
rundeps    :
    - devel:
        - haskell-async-devel
        - haskell-unliftio-core-devel
networking : yes
setup      : |
    # sed -i "s|Custom|Simple|" typed-process.cabal
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
